# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180728_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Teacher'),
        ),
    ]
