# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180728_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incricoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Student')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Course')),
            ],
        ),
    ]
