# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_incricoes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incricoes',
            new_name='Inscricoes',
        ),
    ]
