# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180728_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_grade', models.DecimalField(decimal_places=2, max_digits=4)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student')),
            ],
        ),
        migrations.CreateModel(
            name='SkillIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=300)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=4)),
                ('score_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ScoreRecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='inscricoes',
            name='id_aluno',
        ),
        migrations.RemoveField(
            model_name='inscricoes',
            name='id_curso',
        ),
        migrations.DeleteModel(
            name='Inscricoes',
        ),
    ]
