# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180728_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillindex',
            name='score_record',
        ),
        migrations.RemoveField(
            model_name='skillindex',
            name='student',
        ),
        migrations.AddField(
            model_name='scorerecord',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='sem_nome', max_length=100),
        ),
        migrations.DeleteModel(
            name='SkillIndex',
        ),
    ]
