# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180728_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SkillIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=4)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Skill')),
            ],
        ),
        migrations.AddField(
            model_name='scorerecord',
            name='skill_index',
            field=models.ManyToManyField(to='core.SkillIndex'),
        ),
    ]
