# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180728_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='skill',
        ),
        migrations.RemoveField(
            model_name='skillindex',
            name='skill',
        ),
    ]
