# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180728_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillindex',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Skill'),
            preserve_default=False,
        ),
    ]
